// <auto-generated />
using System;
using AvaBot.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvaBot.Infra.Migrations
{
    [DbContext(typeof(AvaBotContext))]
    partial class AvaBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvaBot.Domain.Models.Agent", b =>
                {
                    b.Property<long>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AgentId"));

                    b.Property<string>("ChatModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("gpt-4o")
                        .HasColumnName("chat_model");

                    b.Property<bool>("CollectEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_email");

                    b.Property<bool>("CollectName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_name");

                    b.Property<bool>("CollectPhone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("OpenAIApiKeyEncrypted")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("openai_api_key_encrypted");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<bool>("PowerBIEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("powerbi_enabled");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<string>("TelegramBotName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("telegram_bot_name");

                    b.Property<string>("TelegramBotToken")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("telegram_bot_token");

                    b.Property<string>("TelegramWebhookSecret")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("telegram_webhook_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatsappToken")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("whatsapp_token");

                    b.HasKey("AgentId")
                        .HasName("avabot_agents_pkey");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_avabot_agents_owner_user_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("avabot_agents_slug_key");

                    b.HasIndex("TelegramBotToken")
                        .IsUnique()
                        .HasDatabaseName("ix_avabot_agents_telegram_bot_token")
                        .HasFilter("telegram_bot_token IS NOT NULL");

                    b.HasIndex("WhatsappToken")
                        .IsUnique()
                        .HasDatabaseName("ix_avabot_agents_whatsapp_token")
                        .HasFilter("whatsapp_token IS NOT NULL");

                    b.ToTable("avabot_agents", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.AgentPowerBIConfig", b =>
                {
                    b.Property<long>("AgentPowerBIConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("agent_powerbi_config_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AgentPowerBIConfigId"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("client_secret_encrypted");

                    b.Property<string>("ClientSecretHint")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("client_secret_hint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastTestAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_test_at");

                    b.Property<string>("LastTestMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_test_message");

                    b.Property<bool?>("LastTestSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("last_test_success");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentPowerBIConfigId")
                        .HasName("avabot_agent_powerbi_configs_pkey");

                    b.HasIndex("AgentId")
                        .IsUnique()
                        .HasDatabaseName("avabot_agent_powerbi_configs_agent_id_key");

                    b.ToTable("avabot_agent_powerbi_configs", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.ChatMessage", b =>
                {
                    b.Property<long>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ChatMessageId"));

                    b.Property<long?>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer")
                        .HasColumnName("sender_type");

                    b.HasKey("ChatMessageId")
                        .HasName("avabot_chat_messages_pkey");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("avabot_chat_messages", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.ChatSession", b =>
                {
                    b.Property<long>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ChatSessionId"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ResumeToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resume_token");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_phone");

                    b.HasKey("ChatSessionId")
                        .HasName("avabot_chat_sessions_pkey");

                    b.HasIndex("AgentId");

                    b.HasIndex("ResumeToken")
                        .IsUnique()
                        .HasDatabaseName("ix_avabot_chat_sessions_resume_token");

                    b.ToTable("avabot_chat_sessions", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.KnowledgeFile", b =>
                {
                    b.Property<long>("KnowledgeFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("KnowledgeFileId"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("ProcessingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("KnowledgeFileId")
                        .HasName("avabot_knowledge_files_pkey");

                    b.HasIndex("AgentId");

                    b.ToTable("avabot_knowledge_files", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.PowerBIDataset", b =>
                {
                    b.Property<long>("PowerBIDatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("powerbi_dataset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("PowerBIDatasetId"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("SchemaError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("schema_error");

                    b.Property<DateTime?>("SchemaGeneratedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("schema_generated_at");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_json");

                    b.Property<int>("SchemaStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("schema_status");

                    b.Property<string>("ToolKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tool_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("workspace_id");

                    b.HasKey("PowerBIDatasetId")
                        .HasName("avabot_powerbi_datasets_pkey");

                    b.HasIndex("AgentId", "DatasetId")
                        .IsUnique()
                        .HasDatabaseName("avabot_powerbi_datasets_agent_id_dataset_id_key");

                    b.HasIndex("AgentId", "ToolKey")
                        .IsUnique()
                        .HasDatabaseName("avabot_powerbi_datasets_agent_id_tool_key_key");

                    b.ToTable("avabot_powerbi_datasets", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.PowerBIQueryLog", b =>
                {
                    b.Property<long>("PowerBIQueryLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("powerbi_query_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("PowerBIQueryLogId"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<long?>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("dataset_name");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long?>("PowerBIDatasetId")
                        .HasColumnType("bigint")
                        .HasColumnName("powerbi_dataset_id");

                    b.Property<string>("Query")
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tool_name");

                    b.Property<bool>("Truncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("truncated");

                    b.Property<string>("UserQuestion")
                        .HasColumnType("text")
                        .HasColumnName("user_question");

                    b.HasKey("PowerBIQueryLogId")
                        .HasName("avabot_powerbi_query_logs_pkey");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("PowerBIDatasetId");

                    b.HasIndex("AgentId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_avabot_powerbi_query_logs_agent_id_created_at");

                    b.ToTable("avabot_powerbi_query_logs", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.TelegramChat", b =>
                {
                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<long>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TelegramFirstName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("telegram_first_name");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("telegram_username");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TelegramChatId")
                        .HasName("avabot_telegram_chats_pkey");

                    b.HasIndex("AgentId");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("avabot_telegram_chats", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("avabot_users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("avabot_users_email_key");

                    b.ToTable("avabot_users", (string)null);
                });

            modelBuilder.Entity("AvaBot.Domain.Models.Agent", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.User", "Owner")
                        .WithMany("Agents")
                        .HasForeignKey("OwnerUserId")
                        .HasConstraintName("avabot_fk_users_agents");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.AgentPowerBIConfig", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.Agent", "Agent")
                        .WithOne("PowerBIConfig")
                        .HasForeignKey("AvaBot.Domain.Models.AgentPowerBIConfig", "AgentId")
                        .IsRequired()
                        .HasConstraintName("avabot_fk_agents_agent_powerbi_configs");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.ChatMessage", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("avabot_fk_chat_sessions_chat_messages");

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.ChatSession", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.Agent", "Agent")
                        .WithMany("ChatSessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("avabot_fk_agents_chat_sessions");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.KnowledgeFile", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.Agent", "Agent")
                        .WithMany("KnowledgeFiles")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("avabot_fk_agents_knowledge_files");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.PowerBIDataset", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.Agent", "Agent")
                        .WithMany("PowerBIDatasets")
                        .HasForeignKey("AgentId")
                        .IsRequired()
                        .HasConstraintName("avabot_fk_agents_powerbi_datasets");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.PowerBIQueryLog", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .IsRequired()
                        .HasConstraintName("avabot_fk_agents_powerbi_query_logs");

                    b.HasOne("AvaBot.Domain.Models.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .HasConstraintName("avabot_fk_chat_sessions_powerbi_query_logs");

                    b.HasOne("AvaBot.Domain.Models.PowerBIDataset", "PowerBIDataset")
                        .WithMany()
                        .HasForeignKey("PowerBIDatasetId")
                        .HasConstraintName("avabot_fk_powerbi_datasets_powerbi_query_logs");

                    b.Navigation("Agent");

                    b.Navigation("ChatSession");

                    b.Navigation("PowerBIDataset");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.TelegramChat", b =>
                {
                    b.HasOne("AvaBot.Domain.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("avabot_fk_telegram_chat_agent");

                    b.HasOne("AvaBot.Domain.Models.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("avabot_fk_telegram_chat_session");

                    b.Navigation("Agent");

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.Agent", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("KnowledgeFiles");

                    b.Navigation("PowerBIConfig");

                    b.Navigation("PowerBIDatasets");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("AvaBot.Domain.Models.User", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
